apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: echoservice
  name: curlpod
spec:
  selector:
    matchLabels:
      app: curlpod
  replicas: 1
  template:
    metadata:
      labels:
        app: curlpod
        ltest: ltest
    spec:
      containers:
      - name: curlpod
        image: tmforumodacanvas/baseimage-kubectl-curl:1.30.5
        imagePullPolicy: Always
        command: ["/bin/sh", "-c", "--"]
        args: [ "echo curlpod started;
        while true; do
		echo;
        curl -s http://echoservice.echoservice.svc.cluster.local/ip;
		sleep 15;
        done"]
  
