apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  namespace: code-server
  name: code-server-vs
  labels:
    app: code-server
spec:
  gateways:
  - {{ .Values.componentGateway }}
  hosts:
  - code-server.{{ .Values.domain }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: code-server.code-server.svc.cluster.local
        port:
          number: 8080
