apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  namespace: echoservice
  name: echoservice-vs
  labels:
    app: echoservice
spec:
  gateways:
  - canvas/component-gateway
  hosts:
  - echoservice.{{ .Values.domain }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: echoservice.echoservice.svc.cluster.local
        port:
          number: 80
