apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-sidecar-conf
  namespace: echoservice
data:
  image-app.conf: |
    server {
      listen              8443 ssl http2;
      server_name         echoservice-tls.echoservice.svc.cluster.local;
      ssl_certificate     /certs/tls.crt;
      ssl_certificate_key /certs/tls.key;
      ssl_session_cache   shared:SSL:10m;
      ssl_session_timeout 1h;
      ssl_buffer_size     8k;

      location / {
          proxy_pass         http://0.0.0.0:8080;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
          proxy_set_header   Upgrade $http_upgrade;
          proxy_set_header   Connection 'upgrade';
          proxy_cache_bypass $http_upgrade;
      }
    }    