apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dummy-cert-for-root-ca
  namespace: cert-manager
spec:
  commonName: dummy-cert-for-root-ca
  dnsNames:
  - dummy-cert-for-root-ca
  duration: 21600h0m0s
  issuerRef:
    name: canvas-cert-manager-init-selfsigned-cluster
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  secretName: canvas-cert-manager-init-selfsigned-cluster-ca
  usages:
  - digital signature
  - content commitment
  - key encipherment
  - server auth
