apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  namespace: echoservice
  name: distribute-cm-root-cas # The bundle name will also be used for the target
spec:
  sources:
  - useDefaultCAs: true
  - secret:
      name: "canvas-cert-manager-init-selfsigned-cluster-ca"
      key: "tls.crt"

  target:
    configMap:
      key: "cm-root-cas.pem"
    namespaceSelector:
      matchLabels:
        injectcmrootcas: "enabled"
