apiVersion: v1
kind: Pod
metadata:
  name: python-debug-pod
  namespace: test
spec:
  containers:
   - name: python-debug-pod
     image: ocfork:alligator-feature-helmdemo
     command: ["python"]
     args: ["-u", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "app.py"]
     imagePullPolicy: Always
  restartPolicy: Never
  
