---
apiVersion: v1
kind: Secret
metadata:
  namespace: hcv
  name: hcv-secrets
type: Opaque
data:
  rootToken: aHZzLnl2WEI4YkFwcmdmdThXcWttZVlaS2NxYQ==
  unsealKey1: UFZJS3VBMyswNkN5Z25mZU1CYmgvWWJqekhhcUpwNlFGb05CRjNOclprRT0=
